
// Meta data for the page 
export const metadata =  {
  title: "About page ",
  description: "Generated by Muhammad hassan",
};

export default function About() {
  return (
    // senario 2
    <h1>About Page ...</h1>
  );
}