import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title :  {
    default : "Next Js tutorial",
    template : "%s | Nesxt Js toturial ", // s% is perfer aboutpage / blog tilte
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="p-10 bg-green-300">
HEADER
        </header>
        {children}
        <footer className="p-10 bg-slate-400">FOOTER</footer>
      </body>
    </html>
  );
}
